Shap Hell's Gate: SharpHellsGate.Module.SystemModule Class Reference
SharpHellsGate.Module.SystemModule Class Reference
Wrapper around the NTDLL module. Used to extract structures and find system calls.
Public Member Functions
SystemModule (string name)
.ctor
bool LoadModule ()
Load the module into a memory stream.
bool LoadAllStructures ()
Reload all structures.
Structures.IMAGE_DOS_HEADER GetModuleDOSHeader (bool ReloadCache=false)
Get the _IMAGE_DOS_HEADERstructure from the module.
Structures.IMAGE_NT_HEADERS64 GetModuleNTHeaders (bool ReloadCache=false)
Get the IMAGE_NT_HEADERS64 structure from the module.
List< Structures.IMAGE_SECTION_HEADER > GetModuleSectionHeaders (bool ReloadCache=false)
Get list of _IMAGE_SECTION_HEADER structures from the module.
Structures.IMAGE_SECTION_HEADER GetModuleSectionHeaderByName (string name)
Get a _IMAGE_SECTION_HEADER structure by name.
Structures.IMAGE_EXPORT_DIRECTORY GetModuleExportDirectory (bool ReloadCache=false)
Get the Export Address Table (aka EAT) from the module.
Util.APITableEntry GetAPITableEntry (UInt64 FunctionHash)
Get the address, name, system call for a given function hash.
Public Member Functions inherited from SharpHellsGate.Module.MemoryUtil
void Dispose ()
Dispose the memory stream when no longer needed.
Properties
Structures.IMAGE_DOS_HEADER ModuleDOSHeader [get, private set]
IMAGE_DOS_HEADER structure of the NTDLL module.
Structures.IMAGE_NT_HEADERS64 ModuleNTHeaders [get, private set]
IMAGE_NT_HEADERS64 structure of the NTDLL module.
List< Structures.IMAGE_SECTION_HEADER > ModuleSectionHeaders [get, private set]
IMAGE_SECTION_HEADER structure from the NTDLL module.
Structures.IMAGE_EXPORT_DIRECTORY ModuleExportDirectory [get, private set]
IMAGE_EXPORT_DIRECTORY structure from the NTDLL module.
Int64 ModuleExportDirectoryOffset [get, private set]
Location in the memory stream of the IMAGE_EXPORT_DIRECTORY structure.
Int64 ModuleExportDirectoryAddressNamesOffset [get, private set]
Location in the memory stream of the exported functions' name.
Int64 ModuleExportDirectoryAddressFunctionsOffset [get, private set]
Location in the memory stream of the exported functions' address.
Int64 ModuleExportDirectoryAddressNameOrdinalesOffset [get, private set]
Location in the memory stream of the exported functions' ordinal.
string ModuleName [get, private set]
Name of the module. Will be NTDLL.
string ModulePath [get, private set]
Path of the module. Will be WINDIR%\System32\ntdll.dll
Properties inherited from SharpHellsGate.Module.MemoryUtil
Stream ModuleStream [get, set]
The memory stream representation of the NTDLL module.
Private Member Functions
Int64 GetModuleSectionOffset (Int16 cx)
Get the offset of a _IMAGE_SECTION_HEADER structure.
Int64 ConvertRvaToOffset (Int64 rva, Structures.IMAGE_SECTION_HEADER SectionHeader)
Convert a relative virtual address (RVA) into an offset.
Int64 ConvertRvaToOffset (Int64 rva)
Convert a relative virtual address (RVA) into an offset.
Structures.IMAGE_SECTION_HEADER GetSectionByRVA (Int64 rva)
Get which image section is which a relative virtual address (RVA) points to.
Additional Inherited Members
Protected Member Functions inherited from SharpHellsGate.Module.MemoryUtil
T GetStructureFromBlob< T > (Int64 offset)
Extract a structure from the memory stream.
Span< byte > GetFunctionOpCode (Int64 offset)
Extract the code from a native Windows function.
UInt32 ReadPtr32 (Int64 offset)
Extract a DWORD value from the memory stream.
UInt64 ReadPtr64 (Int64 offset)
Extract a QWORD value from the memory stream.
UInt16 ReadUShort (Int64 offset)
Extract a WORD value from the memory stream.
string ReadAscii (Int64 offset)
Extract an ASCII string from the memory stream.
Span< byte > GetStructureBytesFromOffset< T > (Int64 offset)
Extract the byte representation of a structure from the memory stream.
Span< byte > GetBytesFromOffset (Int64 offset, int size)
Get a specific amount of bytes at a specific location in the memory stream.
Detailed Description
Wrapper around the NTDLL module. Used to extract structures and find system calls.
Definition at line 14 of file SystemModule.cs.
Constructor & Destructor Documentation
SystemModule()
SharpHellsGate.Module.SystemModule.SystemModule (string name) inline
.ctor
Parameters
name Name of the module
Definition at line 70 of file SystemModule.cs.
                                          : base() {
             this.ModuleName = name;
             this.ModulePath = $"{Environment.SystemDirectory}\\{name}";
             this.ModuleSectionHeaders = new List<Structures.IMAGE_SECTION_HEADER>() { };
             this.LoadModule();
         }
Member Function Documentation
ConvertRvaToOffset() [1/2]
Int64 SharpHellsGate.Module.SystemModule.ConvertRvaToOffset (Int64 rva) private
Convert a relative virtual address (RVA) into an offset.
Parameters
rva The RVA to convert into an offset in the iamge.
Returns
The offset.
ConvertRvaToOffset() [2/2]
Int64 SharpHellsGate.Module.SystemModule.ConvertRvaToOffset (Int64 rva, Structures.IMAGE_SECTION_HEADER SectionHeader) private
Convert a relative virtual address (RVA) into an offset.
Parameters
rva The RVA to convert into an offset in the iamge.
SectionHeader The section in which the relative virtual address (RVA) points to.
Returns
The offset.
Referenced by SharpHellsGate.Module.SystemModule.GetAPITableEntry(), and SharpHellsGate.Module.SystemModule.GetModuleExportDirectory().
GetAPITableEntry()
Util.APITableEntry SharpHellsGate.Module.SystemModule.GetAPITableEntry (UInt64 FunctionHash) inline
Get the address, name, system call for a given function hash.
Parameters
FunctionHash DJB2 function hash.
Returns
Definition at line 261 of file SystemModule.cs.
{
             if (this.ModuleExportDirectoryAddressNamesOffset == 0x00 || this.ModuleExportDirectoryAddressFunctionsOffset == 0x00|| this.ModuleExportDirectoryAddressNameOrdinalesOffset == 0x00)
                 this.GetModuleExportDirectory();
             if (!base.ModuleStream.CanRead || base.ModuleStream.Length == 0x00) {
                 Util.LogError("Module not loaded");
                 return default;
             }
             Util.APITableEntry Entry = new Util.APITableEntry {
                 Hash = FunctionHash
             };
             for (Int32 cx = 0; cx < this.ModuleExportDirectory.NumberOfNames; cx++) {
                 UInt32 PtrFunctionName = base.ReadPtr32(this.ModuleExportDirectoryAddressNamesOffset + (sizeof(uint) * cx));
                 string FunctionName = base.ReadAscii(this.ConvertRvaToOffset(PtrFunctionName));
                 if (FunctionHash == Util.GetFunctionDJB2Hash(FunctionName)) {
                     UInt32 PtrFunctionAdddress = base.ReadPtr32(this.ModuleExportDirectoryAddressFunctionsOffset + (sizeof(uint) * (cx + 1)));
                     Span<byte> opcode = base.GetFunctionOpCode(this.ConvertRvaToOffset(PtrFunctionAdddress));
                     if (opcode[3] == 0xb8 && opcode[18] == 0x0f && opcode[19] == 0x05) {
                         Entry.Name = FunctionName;
                         Entry.Address = PtrFunctionAdddress;
                         Entry.Syscall = (Int16)(((byte)opcode[5] << 4) | (byte)opcode[4]);
                         return Entry;
                     }
                 }
             }
             return default;
         }
Referenced by SharpHellsGate.Program.Main().
GetModuleDOSHeader()
Structures.IMAGE_DOS_HEADER SharpHellsGate.Module.SystemModule.GetModuleDOSHeader (bool ReloadCache = false) inline
Get the _IMAGE_DOS_HEADERstructure from the module.
Parameters
ReloadCache Whether the data has to re-processed if not already cached.
Returns
The IMAGE_NT_HEADERS64 structure of the module.
Definition at line 128 of file SystemModule.cs.
{
             if (!this.ModuleDOSHeader.Equals(default(Structures.IMAGE_DOS_HEADER)) && !ReloadCache)
                 return this.ModuleDOSHeader;
             if (!base.ModuleStream.CanRead || base.ModuleStream.Length == 0x00) {
                 Util.LogError("Module not loaded");
                 return default;
             }
             this.ModuleDOSHeader = base.GetStructureFromBlob<Structures.IMAGE_DOS_HEADER>(0);
             if (this.ModuleDOSHeader.e_magic != Macros.IMAGE_DOS_SIGNATURE) {
                 Util.LogError("Invalid DOS header signature");
                 return default;
             }
             return this.ModuleDOSHeader;
         }
Referenced by SharpHellsGate.Module.SystemModule.GetModuleNTHeaders(), and SharpHellsGate.Module.SystemModule.LoadAllStructures().
GetModuleExportDirectory()
Structures.IMAGE_EXPORT_DIRECTORY SharpHellsGate.Module.SystemModule.GetModuleExportDirectory (bool ReloadCache = false) inline
Get the Export Address Table (aka EAT) from the module.
Parameters
ReloadCache Whether the data has to re-processed if not already cached.
Returns
the _IMAGE_EXPORT_DIRECTORY structure
Definition at line 227 of file SystemModule.cs.
{
             if (!this.ModuleExportDirectory.Equals(default(Structures.IMAGE_EXPORT_DIRECTORY)) && !ReloadCache)
                 return this.ModuleExportDirectory;
             if (!base.ModuleStream.CanRead || base.ModuleStream.Length == 0x00) {
                 Util.LogError("Module not loaded");
                 return default;
             }
             if (this.ModuleNTHeaders.Equals(default(Structures.IMAGE_NT_HEADERS64)))
                 this.GetModuleNTHeaders();
             if (this.ModuleSectionHeaders.Count == 0x00)
                 this.GetModuleSectionHeaders();
             this.ModuleExportDirectoryOffset = this.ConvertRvaToOffset(this.ModuleNTHeaders.OptionalHeader.DataDirectory[0].VirtualAddress);
             this.ModuleExportDirectory = base.GetStructureFromBlob<Structures.IMAGE_EXPORT_DIRECTORY>(this.ModuleExportDirectoryOffset);
             if (this.ModuleExportDirectory.Equals(default(Structures.IMAGE_EXPORT_DIRECTORY))) {
                 Util.LogError("Invalid export address table (EAT).");
                 return default;
             }
             // Parse all functions
             this.ModuleExportDirectoryAddressNamesOffset = this.ConvertRvaToOffset(this.ModuleExportDirectory.AddressOfNames);
             this.ModuleExportDirectoryAddressFunctionsOffset = this.ConvertRvaToOffset(this.ModuleExportDirectory.AddressOfFunctions);
             this.ModuleExportDirectoryAddressNameOrdinalesOffset = this.ConvertRvaToOffset(this.ModuleExportDirectory.AddressOfNameOrdinals);
             return this.ModuleExportDirectory;
         }
Referenced by SharpHellsGate.Module.SystemModule.GetAPITableEntry(), and SharpHellsGate.Module.SystemModule.LoadAllStructures().
GetModuleNTHeaders()
Structures.IMAGE_NT_HEADERS64 SharpHellsGate.Module.SystemModule.GetModuleNTHeaders (bool ReloadCache = false) inline
Get the IMAGE_NT_HEADERS64 structure from the module.
Parameters
ReloadCache Whether the data has to re-processed if not already cached.
Returns
The IMAGE_NT_HEADERS64 structure of the module.
Definition at line 151 of file SystemModule.cs.
{
             if (!this.ModuleNTHeaders.Equals(default(Structures.IMAGE_NT_HEADERS64)) && !ReloadCache)
                 return this.ModuleNTHeaders;
             if (!base.ModuleStream.CanRead || base.ModuleStream.Length == 0x00) {
                 Util.LogError("Module not loaded");
                 return default;
             }
             if (this.ModuleDOSHeader.Equals(default(Structures.IMAGE_DOS_HEADER)))
                 this.GetModuleDOSHeader();
             this.ModuleNTHeaders = base.GetStructureFromBlob<Structures.IMAGE_NT_HEADERS64>(this.ModuleDOSHeader.e_lfanew);
             if (this.ModuleNTHeaders.Signature != Macros.IMAGE_NT_SIGNATURE) {
                 Util.LogError("Invalid NT headers signature");
                 return default;
             }
             return this.ModuleNTHeaders;
         }
Referenced by SharpHellsGate.Module.SystemModule.GetModuleExportDirectory(), SharpHellsGate.Module.SystemModule.GetModuleSectionHeaders(), and SharpHellsGate.Module.SystemModule.LoadAllStructures().
GetModuleSectionHeaderByName()
Structures.IMAGE_SECTION_HEADER SharpHellsGate.Module.SystemModule.GetModuleSectionHeaderByName (string name) inline
Get a _IMAGE_SECTION_HEADER structure by name.
Parameters
name The name of the section.
Returns
The _IMAGE_SECTION_HEADER structure if exists.
Definition at line 205 of file SystemModule.cs.
{
             if (name.Length > 8) {
                 Util.LogError("Invalid section name");
                 return default;
             }
             if (!base.ModuleStream.CanRead || base.ModuleStream.Length == 0x00) {
                 Util.LogError("Module not loaded");
                 return default;
             }
             if (this.ModuleSectionHeaders.Count == 0x00)
                 this.GetModuleSectionHeaders();
             return this.ModuleSectionHeaders.Where(x => x.Name.Equals(name, StringComparison.OrdinalIgnoreCase)).FirstOrDefault();
         }
GetModuleSectionHeaders()
List<Structures.IMAGE_SECTION_HEADER> SharpHellsGate.Module.SystemModule.GetModuleSectionHeaders (bool ReloadCache = false) inline
Get list of _IMAGE_SECTION_HEADER structures from the module.
Parameters
ReloadCache Whether the data has to re-processed if not already cached.
Returns
The list of _IMAGE_SECTION_HEADER structures.
Definition at line 177 of file SystemModule.cs.
{
             if (this.ModuleSectionHeaders.Count == this.ModuleNTHeaders.FileHeader.NumberOfSections && !ReloadCache)
                 return this.ModuleSectionHeaders;
             if (!base.ModuleStream.CanRead || base.ModuleStream.Length == 0x00) {
                 Util.LogError("Module not loaded");
                 return default;
             }
             if (this.ModuleNTHeaders.Equals(default(Structures.IMAGE_NT_HEADERS64)) || this.ModuleNTHeaders.FileHeader.Equals(default(Structures.IMAGE_FILE_HEADER)))
                 this.GetModuleNTHeaders();
             for (Int16 cx = 0; cx < this.ModuleNTHeaders.FileHeader.NumberOfSections; cx++) {
                 Int64 iSectionOffset = this.GetModuleSectionOffset(cx);
                 Structures.IMAGE_SECTION_HEADER ImageSection = base.GetStructureFromBlob<Structures.IMAGE_SECTION_HEADER>(iSectionOffset);
                 if (!ImageSection.Equals(default(Structures.IMAGE_SECTION_HEADER)))
                     this.ModuleSectionHeaders.Add(ImageSection);
             }
             return this.ModuleSectionHeaders;
         }
Referenced by SharpHellsGate.Module.SystemModule.GetModuleExportDirectory(), SharpHellsGate.Module.SystemModule.GetModuleSectionHeaderByName(), and SharpHellsGate.Module.SystemModule.LoadAllStructures().
GetModuleSectionOffset()
Int64 SharpHellsGate.Module.SystemModule.GetModuleSectionOffset (Int16 cx) private
Get the offset of a _IMAGE_SECTION_HEADER structure.
Parameters
cx The section to get.
Returns
The _IMAGE_SECTION_HEADER structure.
Referenced by SharpHellsGate.Module.SystemModule.GetModuleSectionHeaders().
GetSectionByRVA()
Structures.IMAGE_SECTION_HEADER SharpHellsGate.Module.SystemModule.GetSectionByRVA (Int64 rva) private
Get which image section is which a relative virtual address (RVA) points to.
Parameters
rva The RVA
Returns
The _IMAGE_SECTION_HEADER structure
LoadAllStructures()
bool SharpHellsGate.Module.SystemModule.LoadAllStructures () inline
Reload all structures.
Returns
Whether all structures were successfully reloaded.
Definition at line 107 of file SystemModule.cs.
{
             if (this.GetModuleDOSHeader(true).Equals(default(Structures.IMAGE_DOS_HEADER)))
                 return false;
             if (this.GetModuleNTHeaders(true).Equals(default(Structures.IMAGE_NT_HEADERS64)))
                 return false;
             if (this.GetModuleSectionHeaders(true).Count != this.ModuleNTHeaders.FileHeader.NumberOfSections)
                 return false;
             if (this.GetModuleExportDirectory(true).Equals(default(Structures.IMAGE_EXPORT_DIRECTORY)))
                 return false;
             return true;
         }
Referenced by SharpHellsGate.Program.Main().
LoadModule()
bool SharpHellsGate.Module.SystemModule.LoadModule () inline
Load the module into a memory stream.
Returns
Whether the loading process was a success.
Definition at line 82 of file SystemModule.cs.
{
             if (string.IsNullOrEmpty(this.ModuleName)) {
                 Util.LogError("Module name not provided");
                 return false;
             }
             if (!File.Exists(this.ModulePath)) {
                 Util.LogError($"Unable to find module: {this.ModuleName}");
                 return false;
             }
             ReadOnlySpan<byte> ModuleBlob = File.ReadAllBytes(this.ModulePath);
             if (ModuleBlob.Length == 0x00) {
                 Util.LogError($"Empty module content: {this.ModuleName}");
                 return false;
             }
             base.ModuleStream = new MemoryStream(ModuleBlob.ToArray());
             return true;
         }
Referenced by SharpHellsGate.Module.SystemModule.SystemModule().
Property Documentation
ModuleDOSHeader
Structures.IMAGE_DOS_HEADER SharpHellsGate.Module.SystemModule.ModuleDOSHeader get private set
IMAGE_DOS_HEADER structure of the NTDLL module.
Definition at line 19 of file SystemModule.cs.
 { get; private set; }
Referenced by SharpHellsGate.Module.SystemModule.GetModuleDOSHeader(), and SharpHellsGate.Module.SystemModule.GetModuleNTHeaders().
ModuleExportDirectory
Structures.IMAGE_EXPORT_DIRECTORY SharpHellsGate.Module.SystemModule.ModuleExportDirectory get private set
IMAGE_EXPORT_DIRECTORY structure from the NTDLL module.
Definition at line 34 of file SystemModule.cs.
 { get; private set; }
Referenced by SharpHellsGate.Module.SystemModule.GetAPITableEntry(), and SharpHellsGate.Module.SystemModule.GetModuleExportDirectory().
ModuleExportDirectoryAddressFunctionsOffset
Int64 SharpHellsGate.Module.SystemModule.ModuleExportDirectoryAddressFunctionsOffset get private set
Location in the memory stream of the exported functions' address.
Definition at line 49 of file SystemModule.cs.
 { get; private set; }
Referenced by SharpHellsGate.Module.SystemModule.GetAPITableEntry(), and SharpHellsGate.Module.SystemModule.GetModuleExportDirectory().
ModuleExportDirectoryAddressNameOrdinalesOffset
Int64 SharpHellsGate.Module.SystemModule.ModuleExportDirectoryAddressNameOrdinalesOffset get private set
Location in the memory stream of the exported functions' ordinal.
Definition at line 54 of file SystemModule.cs.
 { get; private set; }
Referenced by SharpHellsGate.Module.SystemModule.GetAPITableEntry(), and SharpHellsGate.Module.SystemModule.GetModuleExportDirectory().
ModuleExportDirectoryAddressNamesOffset
Int64 SharpHellsGate.Module.SystemModule.ModuleExportDirectoryAddressNamesOffset get private set
Location in the memory stream of the exported functions' name.
Definition at line 44 of file SystemModule.cs.
 { get; private set; }
Referenced by SharpHellsGate.Module.SystemModule.GetAPITableEntry(), and SharpHellsGate.Module.SystemModule.GetModuleExportDirectory().
ModuleExportDirectoryOffset
Int64 SharpHellsGate.Module.SystemModule.ModuleExportDirectoryOffset get private set
Location in the memory stream of the IMAGE_EXPORT_DIRECTORY structure.
Definition at line 39 of file SystemModule.cs.
 { get; private set; }
Referenced by SharpHellsGate.Module.SystemModule.GetModuleExportDirectory().
ModuleName
string SharpHellsGate.Module.SystemModule.ModuleName get private set
Name of the module. Will be NTDLL.
Definition at line 59 of file SystemModule.cs.
 { get; private set; }
Referenced by SharpHellsGate.Module.SystemModule.LoadModule(), and SharpHellsGate.Module.SystemModule.SystemModule().
ModuleNTHeaders
Structures.IMAGE_NT_HEADERS64 SharpHellsGate.Module.SystemModule.ModuleNTHeaders get private set
IMAGE_NT_HEADERS64 structure of the NTDLL module.
Definition at line 24 of file SystemModule.cs.
 { get; private set; }
Referenced by SharpHellsGate.Module.SystemModule.GetModuleExportDirectory(), SharpHellsGate.Module.SystemModule.GetModuleNTHeaders(), SharpHellsGate.Module.SystemModule.GetModuleSectionHeaders(), and SharpHellsGate.Module.SystemModule.LoadAllStructures().
ModulePath
string SharpHellsGate.Module.SystemModule.ModulePath get private set
Path of the module. Will be WINDIR%\System32\ntdll.dll
Definition at line 64 of file SystemModule.cs.
 { get; private set; }
Referenced by SharpHellsGate.Module.SystemModule.LoadModule(), and SharpHellsGate.Module.SystemModule.SystemModule().
ModuleSectionHeaders
List<Structures.IMAGE_SECTION_HEADER> SharpHellsGate.Module.SystemModule.ModuleSectionHeaders get private set
IMAGE_SECTION_HEADER structure from the NTDLL module.
Definition at line 29 of file SystemModule.cs.
 { get; private set; }
Referenced by SharpHellsGate.Module.SystemModule.GetModuleExportDirectory(), SharpHellsGate.Module.SystemModule.GetModuleSectionHeaderByName(), SharpHellsGate.Module.SystemModule.GetModuleSectionHeaders(), and SharpHellsGate.Module.SystemModule.SystemModule().
The documentation for this class was generated from the following file:
SharpHellsGate/Module/SystemModule.cs