Shap Hell's Gate: SharpHellsGate.Util Class Reference
SharpHellsGate.Util Class Reference
Util class. Used mainly for debug output.
Classes
struct APITableEntry
Structure used to store the name, address, system call and hash of a native Windows function.
Static Public Member Functions
static void LogInfo (string msg, int indent=0, string prefix="[>]")
Log an informational information.
static void LogError (string msg, int indent=0, string prefix="[-]")
Log an error information.
static void LogSuccess (string msg, int indent=0, string prefix="[+]")
Log a success information.
static UInt64 GetFunctionDJB2Hash (string FunctionName)
Revisited DJB2 algorithm.
Properties
static UInt64 NtAllocateVirtualMemoryHash = 0xf5bd373480a6b89b [get]
DJB2 Hash of the NtAllocateVirtualMemory function name.
static UInt64 NtProtectVirtualMemoryHash = 0x858bcb1046fb6a37 [get]
DJB2 Hash of the NtProtectVirtualMemory function name.
static UInt64 NtCreateThreadExHash = 0x64dc7db288c5015f [get]
DJB2 Hash of the NtCreateThreadEx function name.
static UInt64 NtWaitForSingleObjectHash = 0xc6a2fa174e551bcb [get]
DJB2 Hash of the NtWaitForSingleObject function name.
Static Private Member Functions
static void LogMessage (string msg, string prefix, int indent, ConsoleColor color)
Log a string to the console and to the debugger.
Detailed Description
Util class. Used mainly for debug output.
Definition at line 9 of file Util.cs.
Member Function Documentation
GetFunctionDJB2Hash()
static UInt64 SharpHellsGate.Util.GetFunctionDJB2Hash (string FunctionName) inline static
Revisited DJB2 algorithm.
Parameters
FunctionName The ASCII name of a function.
Returns
The djb2 hash of the function name.
Definition at line 116 of file Util.cs.
{
             if (string.IsNullOrEmpty(FunctionName))
                 return 0;
             UInt64 hash = 0x7734773477347734;
             foreach (char c in FunctionName)
                 hash = ((hash << 0x5) + hash) + (byte)c;
             return hash;
         }
Referenced by SharpHellsGate.Module.SystemModule.GetAPITableEntry().
LogError()
static void SharpHellsGate.Util.LogError (string msg, int indent = 0, string prefix = "[-]") inline static
Log an error information.
Parameters
msg Message to log.
indent Indentation level.
prefix Message prefix.
Definition at line 63 of file Util.cs.
{
 #if DEBUG
             if (string.IsNullOrEmpty(msg))
                 return;
             LogMessage(msg, prefix, indent, ConsoleColor.Red);
 #endif
         }
Referenced by SharpHellsGate.HellsGate.GenerateRWXMemorySegment(), SharpHellsGate.Module.SystemModule.GetAPITableEntry(), SharpHellsGate.Module.SystemModule.GetModuleDOSHeader(), SharpHellsGate.Module.SystemModule.GetModuleExportDirectory(), SharpHellsGate.Module.SystemModule.GetModuleNTHeaders(), SharpHellsGate.Module.SystemModule.GetModuleSectionHeaderByName(), SharpHellsGate.Module.SystemModule.GetModuleSectionHeaders(), SharpHellsGate.Module.SystemModule.LoadModule(), SharpHellsGate.Program.Main(), SharpHellsGate.HellsGate.NtInvocation< T >(), and SharpHellsGate.HellsGate.Payload().
LogInfo()
static void SharpHellsGate.Util.LogInfo (string msg, int indent = 0, string prefix = "[>]") inline static
Log an informational information.
Parameters
msg Message to log.
indent Indentation level.
prefix Message prefix.
Definition at line 48 of file Util.cs.
{
 #if DEBUG
             if (string.IsNullOrEmpty(msg))
                 return;
             LogMessage(msg, prefix, indent, ConsoleColor.Blue);
 #endif
         }
Referenced by SharpHellsGate.HellsGate.GenerateRWXMemorySegment(), SharpHellsGate.Program.Main(), and SharpHellsGate.HellsGate.Payload().
LogMessage()
static void SharpHellsGate.Util.LogMessage (string msg, string prefix, int indent, ConsoleColor color) inline static private
Log a string to the console and to the debugger.
Parameters
msg Message to log.
indent Indentation level.
prefix Message prefix.
color The color of the prifix on the console.
Definition at line 94 of file Util.cs.
{
             // Indent
             Console.Write(new String(' ', indent));
             Trace.Write(new String(' ', indent));
             // Color and prefix
             Trace.Write(prefix);
             Console.ForegroundColor = color;
             Console.Write(prefix);
             Console.ResetColor();
             // Message
             Console.WriteLine($" {msg}");
             Trace.WriteLine($" {msg}");
         }
Referenced by SharpHellsGate.Util.LogError(), SharpHellsGate.Util.LogInfo(), and SharpHellsGate.Util.LogSuccess().
LogSuccess()
static void SharpHellsGate.Util.LogSuccess (string msg, int indent = 0, string prefix = "[+]") inline static
Log a success information.
Parameters
msg Message to log.
indent Indentation level.
prefix Message prefix
Definition at line 78 of file Util.cs.
{
 #if DEBUG
             if (string.IsNullOrEmpty(msg))
                 return;
             LogMessage(msg, prefix, indent, ConsoleColor.Green);
 #endif
         }
Property Documentation
NtAllocateVirtualMemoryHash
UInt64 SharpHellsGate.Util.NtAllocateVirtualMemoryHash = 0xf5bd373480a6b89b static get
DJB2 Hash of the NtAllocateVirtualMemory function name.
Definition at line 24 of file Util.cs.
 { get; } = 0xf5bd373480a6b89b;
Referenced by SharpHellsGate.Program.Main(), and SharpHellsGate.HellsGate.NtAllocateVirtualMemory().
NtCreateThreadExHash
UInt64 SharpHellsGate.Util.NtCreateThreadExHash = 0x64dc7db288c5015f static get
DJB2 Hash of the NtCreateThreadEx function name.
Definition at line 34 of file Util.cs.
 { get; } = 0x64dc7db288c5015f;
Referenced by SharpHellsGate.Program.Main(), and SharpHellsGate.HellsGate.NtCreateThreadEx().
NtProtectVirtualMemoryHash
UInt64 SharpHellsGate.Util.NtProtectVirtualMemoryHash = 0x858bcb1046fb6a37 static get
DJB2 Hash of the NtProtectVirtualMemory function name.
Definition at line 29 of file Util.cs.
 { get; } = 0x858bcb1046fb6a37;
Referenced by SharpHellsGate.Program.Main(), and SharpHellsGate.HellsGate.NtProtectVirtualMemory().
NtWaitForSingleObjectHash
UInt64 SharpHellsGate.Util.NtWaitForSingleObjectHash = 0xc6a2fa174e551bcb static get
DJB2 Hash of the NtWaitForSingleObject function name.
Definition at line 39 of file Util.cs.
 { get; } = 0xc6a2fa174e551bcb;
Referenced by SharpHellsGate.Program.Main(), and SharpHellsGate.HellsGate.NtWaitForSingleObject().
The documentation for this class was generated from the following file:
SharpHellsGate/Util.cs