Shap Hell's Gate: SharpHellsGate.Win32.DFunctions Class Reference
SharpHellsGate.Win32.DFunctions Class Reference
Contains all the delegates used to execute the system calls.
Public Member Functions
delegate uint NtAllocateVirtualMemory (IntPtr ProcessHandle, ref IntPtr BaseAddress, IntPtr ZeroBits, ref IntPtr RegionSize, UInt32 AllocationType, UInt32 Protect)
Managed wrapper around the NtAllocateVirtualMemory native Windows function
delegate uint NtProtectVirtualMemory (IntPtr ProcessHandle, ref IntPtr BaseAddress, ref IntPtr RegionSize, UInt32 NewProtect, out UInt32 OldProtect)
Managed wrapper around the NtProtectVirtualMemory native Windows function.
delegate uint NtCreateThreadEx (ref IntPtr hThread, uint DesiredAccess, IntPtr ObjectAttributes, IntPtr ProcessHandle, IntPtr lpStartAddress, IntPtr lpParameter, bool CreateSuspended, uint StackZeroBits, uint SizeOfStackCommit, uint SizeOfStackReserve, IntPtr lpBytesBuffer)
Managed wrapper around the NtCreateThreadEx native Windows function.
delegate uint NtWaitForSingleObject (IntPtr ObjectHandle, bool Alertable, ref Structures.LARGE_INTEGER TimeOut)
Managed wrapper around the NtWaitForSingleObject native Windows function.
Detailed Description
Contains all the delegates used to execute the system calls.
Definition at line 9 of file DFunctions.cs.
Member Function Documentation
NtAllocateVirtualMemory()
delegate uint SharpHellsGate.Win32.DFunctions.NtAllocateVirtualMemory (IntPtr ProcessHandle, ref IntPtr BaseAddress, IntPtr ZeroBits, ref IntPtr RegionSize, UInt32 AllocationType, UInt32 Protect)
Managed wrapper around the NtAllocateVirtualMemory native Windows function
Parameters
ProcessHandle A handle for the process for which the mapping should be done.
BaseAddress A pointer to a variable that will receive the base address of the allocated region of pages.
ZeroBits The number of high-order address bits that must be zero in the base address of the section view.
RegionSize A pointer to a variable that will receive the actual size, in bytes, of the allocated region of pages.
AllocationType A bitmask containing flags that specify the type of allocation to be performed for the specified region of pages.
Protect A bitmask containing page protection flags that specify the protection desired for the committed region of pages.
Returns
NtAllocateVirtualMemory returns either STATUS_SUCCESS or an error status code.
Referenced by SharpHellsGate.HellsGate.NtAllocateVirtualMemory().
NtCreateThreadEx()
delegate uint SharpHellsGate.Win32.DFunctions.NtCreateThreadEx (ref IntPtr hThread, uint DesiredAccess, IntPtr ObjectAttributes, IntPtr ProcessHandle, IntPtr lpStartAddress, IntPtr lpParameter, bool CreateSuspended, uint StackZeroBits, uint SizeOfStackCommit, uint SizeOfStackReserve, IntPtr lpBytesBuffer)
Managed wrapper around the NtCreateThreadEx native Windows function.
Parameters
hThread Caller supplied storage for the resulting handle.
DesiredAccess Specifies the allowed or desired access to the thread.
ObjectAttributes Initialized attributes for the object.
ProcessHandle Handle to the threads parent process.
lpStartAddress Address of the function to execute.
lpParameter Parameters to pass to the function.
CreateSuspended Whether the thread will be in suspended mode and has to be resumed later.
StackZeroBits
SizeOfStackCommit Initial stack memory to commit.
SizeOfStackReserve Initial stack memory to reserve.
lpBytesBuffer
Returns
NtCreateThreadEx returns either STATUS_SUCCESS or an error status code.
Referenced by SharpHellsGate.HellsGate.NtCreateThreadEx().
NtProtectVirtualMemory()
delegate uint SharpHellsGate.Win32.DFunctions.NtProtectVirtualMemory (IntPtr ProcessHandle, ref IntPtr BaseAddress, ref IntPtr RegionSize, UInt32 NewProtect, out UInt32 OldProtect)
Managed wrapper around the NtProtectVirtualMemory native Windows function.
Parameters
ProcessHandle Handle to Process Object opened with PROCESS_VM_OPERATION access.
BaseAddress Pointer to base address to protect. Protection will change on all page containing specified address. On output, BaseAddress will point to page start address.
NumberOfBytesToProtect Pointer to size of region to protect. On output will be round to page size (4KB).
NewAccessProtection One or some of PAGE_... attributes.
OldAccessProtection Receive previous protection.
Returns
NtProtectVirtualMemory returns either STATUS_SUCCESS or an error status code.
Referenced by SharpHellsGate.HellsGate.NtProtectVirtualMemory().
NtWaitForSingleObject()
delegate uint SharpHellsGate.Win32.DFunctions.NtWaitForSingleObject (IntPtr ObjectHandle, bool Alertable, ref Structures.LARGE_INTEGER TimeOut)
Managed wrapper around the NtWaitForSingleObject native Windows function.
Parameters
ObjectHandle Open handle to a alertable executive object.
Alertable If set, calling thread is signaled, so all queued APC routines are executed.
TimeOuts Time-out interval, in microseconds. NULL means infinite.
Returns
NtWaitForSingleObject returns either STATUS_SUCCESS or an error status code.
Referenced by SharpHellsGate.HellsGate.NtWaitForSingleObject().
The documentation for this class was generated from the following file:
SharpHellsGate/Win32/DFunctions.cs